---
- name: Install fileserver packages
  hosts: fileservers
  tasks:
    - name: Includes the variable
      include_vars: package.yml

    - name: Installs the package
      include_tasks: install_package.yml
    
    - name: Installs the package
      ansible.builtin.include_tasks: 
        file: install_package.yml
      vars:
        package:
          web_pkg: epel-release
    
    - name: Installs the package
      ansible.builtin.include_tasks: 
        file: install_package.yml
      vars:
        package:
          web_pkg: tomcat
    
    