---
- name:  restrore the playbook.yml
  hosts: all
  gather_facts: true
  tasks:
    #1  방화벽 닫기
    #2 서비스 내리기
    #3 웹서비스 설정 삭제
    #4 패키지 삭제 
    #5 팩트 삭제
  - name: 방화벽 닫기
    firewalld:
      service: "{{ item }}"
      permanent: yes
      immediate: yes
      state: disabled
    with items:
      - http
      - https
  - name: 서비스 내리기
    service:
      name: "{{ item }}"
      state: stopped
    with items:
      - firewalld
      - httpd
  - name: 웹 서비스 설정 삭제
    file:
      path: /var/www/html/index.html
      state: absent
  - name:  패키지 삭제
    yum:
      name: 
        - htppd
        - firewalld
      state: absent
  - name: 사용자 정의 팩트 삭제
    file:
      path: /etc/ansible/facts.d
      state: absent  