---
- name: 복원 작업 수행
  hosts: all
  tasks:
    - name: MariaDB 서비스 비활성화
      service:
        name: mariadb
        state: stopped
        enabled: no

    - name: MariaDB 서버 패키지 삭제
      yum:
        name: mariadb-server
        state: absent
